<a href="https://colab.research.google.com/github/jrevault/ai_stuff/blob/main/PYTORCH_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


Creating tensors
https://pytorch.org/docs/stable/tensors.html

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.ndim

0

In [6]:
matrix = torch.tensor(
    [
        [[1,2,3],[1,2,3],[1,2,3]],
        [[1,2,3],[1,2,3],[1,2,3]]
    ]
)
matrix.shape

torch.Size([2, 3, 3])

In [7]:
matrix.ndim

3

Random tensors

In [8]:
rand_tensor = torch.rand(size=(3,4))
rand_tensor.shape

torch.Size([3, 4])

In [9]:
rand_tensor

tensor([[0.5953, 0.3571, 0.7507, 0.0331],
        [0.7711, 0.4056, 0.3776, 0.0950],
        [0.9609, 0.0702, 0.0286, 0.9197]])

In [10]:
rand_tensor.ndim

2

In [11]:
img_tensor = torch.rand(size=(224,224,3))
img_tensor.shape, img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
one_2_10 = torch.arange(start=1, end=10, step=1)
one_2_10

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ten_z = torch.zeros_like(input=one_2_10)
ten_z

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
float_tensor = torch.tensor(
    data=[3.0, 4.5, 9.0], 
    dtype=None, 
    device=None # "cpu" "cuda"
)
float_tensor, float_tensor.dtype

(tensor([3.0000, 4.5000, 9.0000]), torch.float32)

In [15]:
rand_tens = torch.rand(size=(2,3))
rand_tens

tensor([[0.7113, 0.7683, 0.8175],
        [0.4739, 0.9153, 0.8814]])

In [16]:
int_32 = torch.tensor(data=[1,2,3], dtype=torch.int32)
float_16 = torch.tensor(data=[1.1,2.1, 3.1], dtype=torch.float16)
float_16 * int_32

tensor([1.0996, 4.1992, 9.2969], dtype=torch.float16)

In [17]:
rand_tens = torch.rand(size=(2,3))
print(rand_tens)
print(f"Datatype: {rand_tens.dtype}")
print(f"Shape   : {rand_tens.shape}")
print(f"Device  : {rand_tens.device}")

tensor([[0.2140, 0.0542, 0.8803],
        [0.8183, 0.8905, 0.6499]])
Datatype: torch.float32
Shape   : torch.Size([2, 3])
Device  : cpu


Tensor operations

In [18]:
rand_tens = torch.tensor(data=[1,2,3], dtype=torch.int32)
rand_tens

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
rand_tens + 10

tensor([11, 12, 13], dtype=torch.int32)

In [20]:
rand_tens * 10

tensor([10, 20, 30], dtype=torch.int32)

In [21]:
rand_tens - 5

tensor([-4, -3, -2], dtype=torch.int32)

Matrix multiplication

In [22]:
tens1 = torch.tensor(data=[2,2,2], dtype=torch.int32)
tens2 = torch.tensor(data=[1,2,3], dtype=torch.int32)
tens1 * tens2, torch.matmul(tens1, tens2), tens1 @ tens2

(tensor([2, 4, 6], dtype=torch.int32),
 tensor(12, dtype=torch.int32),
 tensor(12, dtype=torch.int32))

In [23]:
tens1 = torch.tensor(data=[[2,2,2],[3,3,3]], dtype=torch.int32)
tens2 = torch.tensor(data=[[1,2,3],[1,2,3]], dtype=torch.int32)
tens1 * tens2

tensor([[2, 4, 6],
        [3, 6, 9]], dtype=torch.int32)

In [24]:
%%time
tens1 = torch.tensor(
    [[1,2,3],
     [4,5,6]])
tens2 = torch.tensor(
    [[7,8],
     [9,10],
     [11,12]])
tens1 @ tens2

CPU times: user 2.54 ms, sys: 0 ns, total: 2.54 ms
Wall time: 4.86 ms


tensor([[ 58,  64],
        [139, 154]])

Tensor aggregation

In [33]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [37]:
print(f"Min: {torch.min(x)}, max: {torch.max(x)}, median: {torch.median(x)}")
print(f"Min: {x.min()}, max: {x.max()}, median: {x.median()}")
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

Min: 0, max: 90, median: 40
Min: 0, max: 90, median: 40


(tensor(45.), tensor(45.))

POositionnal min and max

In [40]:
x = torch.arange(1, 11, 1)
x, x.argmin(), x.argmax()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), tensor(0), tensor(9))

* Reshaping: shape mismatch,n reshape to a specific shape
* View: show a tensor in a different shape (not changing the original)
* Stacking: torch stack (vstack, hstack) : combine multiple tensors on top of each other
* Squeezing: Removes all '1' dimensions from a tensor
* Unsqueezing: Add a '1' dimensions to a tensor
* Permute: permute the dimensions



In [42]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# Add a dimension
#x_reshaped = x.reshape(1,7) # Error: reshaping a 9 element shape in a 7 element shape : reshape des not no what to do with the 8th and 9th element of the first tensor
#x_reshaped = x.reshape(2,9) # Error: must respect the original shape of 1 dimension containing 9 elements... 1x9 = 9
x_reshaped_1 = x.reshape(1,9) # Adds an extra dimension around all 9 elements: Add 1 dimension of 9 element.. 9x1 = 9
x_reshaped_1, x_reshaped_1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
x_reshaped_2 = x.reshape(9,1) # Add an extra dimension around each elements: Add 9 dimmensions of size 1
x_reshaped_2, x_reshaped_2.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [52]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [53]:
x_reshaped_3 = x.reshape(5,2) # Adds 5 extra dimension around each 2 elements... 5x2 = 10
x_reshaped_3, x_reshaped_3.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), torch.Size([5, 2]))

In [54]:
x_reshaped_4 = x.reshape(2,5) # Adds 5 extra dimension around each 2 elements... 2x5 = 10
x_reshaped_4, x_reshaped_4.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]), torch.Size([2, 5]))

In [55]:
# Let's have fun with 12
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [56]:
x.reshape(1,12)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [57]:
x.reshape(2,6)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [58]:
x.reshape(3,4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [59]:
x.reshape(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [60]:
x.reshape(6,2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [62]:
x.reshape(12,1)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

In [63]:
# Back to original
x = torch.arange(1., 10.)
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])