<a href="https://colab.research.google.com/github/jrevault/ai_stuff/blob/main/PYTORCH_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.0+cu116


Creating tensors
https://pytorch.org/docs/stable/tensors.html

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [5]:
scalar.shape

torch.Size([])

In [7]:
scalar.ndim

0

In [16]:
matrix = torch.tensor(
    [
        [[1,2,3],[1,2,3],[1,2,3]],
        [[1,2,3],[1,2,3],[1,2,3]]
    ]
)
matrix.shape

torch.Size([2, 3, 3])

In [17]:
matrix.ndim

3

Random tensors

In [20]:
rand_tensor = torch.rand(size=(3,4))
rand_tensor.shape

torch.Size([3, 4])

In [21]:
rand_tensor

tensor([[0.9427, 0.9301, 0.9262, 0.8180],
        [0.2810, 0.8262, 0.7977, 0.7252],
        [0.7818, 0.8103, 0.4137, 0.1644]])

In [22]:
rand_tensor.ndim

2

In [23]:
img_tensor = torch.rand(size=(224,224,3))
img_tensor.shape, img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [5]:
one_2_10 = torch.arange(start=1, end=10, step=1)
one_2_10

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
ten_z = torch.zeros_like(input=one_2_10)
ten_z

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
float_tensor = torch.tensor(
    data=[3.0, 4.5, 9.0], 
    dtype=None, 
    device=None # "cpu" "cuda"
)
float_tensor, float_tensor.dtype

(tensor([3.0000, 4.5000, 9.0000]), torch.float32)

In [22]:
rand_tens = torch.rand(size=(2,3))
rand_tens

tensor([[0.6146, 0.7104, 0.0892],
        [0.9103, 0.3199, 0.1239]])

In [26]:
int_32 = torch.tensor(data=[1,2,3], dtype=torch.int32)
float_16 = torch.tensor(data=[1.1,2.1, 3.1], dtype=torch.float16)
float_16 * int_32

tensor([1.0996, 4.1992, 9.2969], dtype=torch.float16)

In [28]:
rand_tens = torch.rand(size=(2,3))
print(rand_tens)
print(f"Datatype: {rand_tens.dtype}")
print(f"Shape   : {rand_tens.shape}")
print(f"Device  : {rand_tens.device}")

tensor([[0.7583, 0.3281, 0.7756],
        [0.4774, 0.0069, 0.5713]])
Datatype: torch.float32
Shape   : torch.Size([2, 3])
Device  : cpu


Tensor operations

In [31]:
rand_tens = torch.tensor(data=[1,2,3], dtype=torch.int32)
rand_tens

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
rand_tens + 10

tensor([11, 12, 13], dtype=torch.int32)

In [34]:
rand_tens * 10

tensor([10, 20, 30], dtype=torch.int32)

In [37]:
rand_tens - 5

tensor([-4, -3, -2], dtype=torch.int32)

Matrix multiplication

In [49]:
tens1 = torch.tensor(data=[2,2,2], dtype=torch.int32)
tens2 = torch.tensor(data=[1,2,3], dtype=torch.int32)
tens1 * tens2, torch.matmul(tens1, tens2), tens1 @ tens2

(tensor([2, 4, 6], dtype=torch.int32),
 tensor(12, dtype=torch.int32),
 tensor(12, dtype=torch.int32))

In [42]:
tens1 = torch.tensor(data=[[2,2,2],[3,3,3]], dtype=torch.int32)
tens2 = torch.tensor(data=[[1,2,3],[1,2,3]], dtype=torch.int32)
tens1 * tens2

tensor([[2, 4, 6],
        [3, 6, 9]], dtype=torch.int32)

In [51]:
%%time
tens1 = torch.tensor(
    [[1,2,3],
     [4,5,6]])
tens2 = torch.tensor(
    [[7,8],
     [9,10],
     [11,12]])
tens1 @ tens2

CPU times: user 718 µs, sys: 1.07 ms, total: 1.78 ms
Wall time: 1.76 ms


tensor([[ 58,  64],
        [139, 154]])